version: '3.6'

networks:
  net:





volumes:
#    prometheus: {}
    grafana: {}



services:

  prometheus:
        image: prom/prometheus:v2.21.0
        networks:
          - net
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        #links:
        #    - cadvisor:cadvisor
        depends_on:
            - cadvisor
            - node_exporter
        restart: always

  grafana:
        image: grafana/grafana:7.1.5
        networks:
          - net
        environment:
         - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
         - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
         - GF_USERS_ALLOW_SIGN_UP=false
      
        volumes:
           - grafana:/var/lib/grafana
        ports:
            - 3000:3000
        restart: always


  cadvisor:
       image: google/cadvisor:v0.33.0
       networks:
           - net
       ports:
       - 8080:8080
       volumes:
           - /:/rootfs:ro
           - /var/run:/var/run:rw
           - /sys:/sys:ro
           - /var/lib/docker/:/var/lib/docker:ro



  node_exporter:
       image: prom/node-exporter:v1.0.1
       networks:
           - net
       volumes:
         - /proc:/host/proc:ro
         - /sys:/host/sys:ro
         - /:/rootfs:ro
         - /etc/hostname:/etc/nodename
       command:
         - '--path.sysfs=/host/sys'
         - '--path.procfs=/host/proc'
         - '--collector.textfile.directory=/etc/node-exporter/'
         - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
         - '--no-collector.ipvs'
#       ports:
#          - 9100:9100
